### ISSUE TITLE
try magicbaidu meet 

### ISSUE THREAD

**Issue by luckrill** [1049451037/MagicBaidu#1]
result['url'] = item.h3.a['href']

input some search key(软件测试  or  International School ) meet: 
TypeError: 'NoneType' object is not subscriptable

**Comment by 1049451037** [comment]
Yeah, there are some exceptions to be tracked...However, maybe I am not available to maintain this repo for now. Welcome pull requests!

**Comment by luckrill** [comment]
start = start // 10 * 10
		content = self.search_page(query, start, pause)
		soup = BeautifulSoup(content, "html.parser")
		now = start + 1
		for item in soup.find_all('div'):
			if item.has_attr('id') and item['id'] == str(now):
				now += 1
				result = {}
				result['title'] = item.h3.get_text()
				result['url'] = item.h3.a['href']
				ss = ''
				for div in item.find_all('div'):
					if div.has_attr('class') and (div['class'][0].find('abstract') != -1 or div['class'][0] == 'c-row'):
						ss += div.get_text()
				result['text'] = ss
				yield result

**Comment by luckrill** [comment]
core code is above, need check current baidu page with code paramter.

**Comment by luckrill** [comment]
我这样评估，设置固定的虚假 URL，之后运行正常。
标题相关的 URL 肯定存在，我们取得 URL的方式应该有问题
读取标签让我很累，页面元素过于复杂。
中文说明吧

**Comment by luckrill** [comment]
today I know how to fix this issue.
